# Generated by Django 5.2.5 on 2025-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermonitoringapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpoint',
            name='raw_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
